# -*- coding: utf-8; tab-width: 4 -*-
# Author: Yasutaka SHINDOH

A := 3
B := 5
M := 13
X := 8

check:
	ruby LCGs.rb -A $(A) -B $(B) -M $(M) -X $(X) 1 2 3 4 5 6 7 8 9 10

clean:
	rm -f *~

.PHONY: check clean
